// scripts/fetch-gilbert-parcels.ts
// One-time capture of Gilbert/Chandler assessor parcels.
// Run via: npx tsx scripts/fetch-gilbert-parcels.ts
//
// Thin orchestration shell — all non-trivial logic lives in ./lib/gilbert-fetch
// and is unit-tested. This file composes those helpers with network I/O.

import fs from "node:fs";
import zlib from "node:zlib";
import {
  stampFeature,
  enforceGzippedBudget,
  nextPage,
  probeEndpoint,
  formatFailLoudMessage,
  type Bbox,
} from "./lib/gilbert-fetch";

const BBOX: Bbox = { xmin: -111.755, ymin: 33.225, xmax: -111.695, ymax: 33.258 };
const OUT_FIELDS = [
  "APN", "APN_DASH", "OWNER_NAME",
  "PHYSICAL_STREET_NUM", "PHYSICAL_STREET_DIR", "PHYSICAL_STREET_NAME",
  "PHYSICAL_STREET_TYPE", "PHYSICAL_CITY", "PHYSICAL_ZIP",
  "SUBNAME", "LOT_NUM", "DEED_NUMBER", "DEED_DATE", "SALE_DATE",
  "LAND_SIZE", "CONST_YEAR", "Shape_Length", "Shape_Area",
].join(",");
const BUDGET = 2 * 1024 * 1024;

const PROBE_URLS = [
  "https://gis.mcassessor.maricopa.gov/arcgis/rest/services/Parcels/MapServer",
  "https://maps.mcassessor.maricopa.gov/arcgis/rest/services/",
  "https://maps-mcassessor.opendata.arcgis.com/",
];

// Layer path convention for the Maricopa Parcels FeatureServer. If the probe
// succeeds at a base URL that does not map to a /0/query endpoint (e.g.,
// open-data portal indirection), fetchPage will fail with a 404 and the
// operator must adjust this or switch to the canonical endpoint.
const LAYER_PATH = "/0";

type Page = { features: unknown[]; exceededTransferLimit?: boolean; count?: number };

async function fetchPage(base: string, offset: number): Promise<{ url: string; page: Page }> {
  const params = new URLSearchParams({
    geometryType: "esriGeometryEnvelope",
    geometry: `${BBOX.xmin},${BBOX.ymin},${BBOX.xmax},${BBOX.ymax}`,
    spatialRel: "esriSpatialRelIntersects",
    outFields: OUT_FIELDS,
    returnGeometry: "true",
    outSR: "4326",
    f: "geojson",
    geometryPrecision: "6",
    resultRecordCount: "2000",
    resultOffset: String(offset),
    inSR: "4326",
  });
  const url = `${base}${LAYER_PATH}/query?${params}`;
  const r = await fetch(url);
  if (!r.ok) throw new Error(`fetch ${r.status} ${url}`);
  return { url, page: (await r.json()) as Page };
}

async function main() {
  // 1. Endpoint probe (all work delegated to tested helpers).
  const probeRes = await probeEndpoint(PROBE_URLS, fetch);
  if (!probeRes.ok) {
    console.error(formatFailLoudMessage(PROBE_URLS));
    console.error("Probe attempts:");
    for (const a of probeRes.attempts) console.error(`  ${a.url}: ${a.error}`);
    process.exit(1);
  }
  const base = probeRes.base;
  console.log(`probe OK: ${base}`);

  // 2. Paginated fetch — tag each feature with captured_date + source_url.
  const captured = new Date().toISOString().slice(0, 10);
  const all: unknown[] = [];
  let offset = 0;
  let lastUrl = "";
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const { url, page } = await fetchPage(base, offset);
    lastUrl = url;
    console.log(`page offset=${offset} → ${page.features?.length ?? 0} features`);
    for (const f of page.features ?? []) {
      all.push(stampFeature(f as never, { source_url: url, captured_date: captured }));
    }
    const next = nextPage(page, offset);
    if (next === null) break;
    offset = next;
  }

  // 3. Assemble the FeatureCollection with a provenance metadata block.
  const out = {
    type: "FeatureCollection" as const,
    metadata: {
      source: "maricopa_assessor_public_gis",
      source_url: lastUrl,
      captured_date: captured,
      record_count: all.length,
      bbox: BBOX,
      attribution: "Maricopa County Assessor",
      legal: "Public record per Arizona A.R.S. § 11-495",
      layer_endpoint: `${base}${LAYER_PATH}`,
    },
    features: all,
  };

  const json = JSON.stringify(out);
  const gz = zlib.gzipSync(Buffer.from(json));

  // 4. Budget check — throws with concrete retry bbox if over.
  enforceGzippedBudget(gz, BUDGET, { bbox: BBOX });

  // 5. Write the data file + the build-time SEED_COUNT constant.
  fs.writeFileSync("src/data/gilbert-parcels-geo.json", json);
  fs.writeFileSync(
    "src/data/gilbert-seed-count.ts",
    `// Generated by scripts/fetch-gilbert-parcels.ts on ${captured}.\n` +
      `// Source of truth for the landing "not in seeded area" copy.\n` +
      `export const SEED_COUNT = ${all.length};\n`,
  );

  console.log(
    `wrote ${all.length} features, ${json.length} bytes raw, ${gz.byteLength} bytes gzipped (budget ${BUDGET})`,
  );
}

main().catch((e) => {
  console.error((e as Error).message);
  process.exit(1);
});
