// scripts/fetch-gilbert-parcels.ts
// One-time capture of Gilbert/Chandler assessor parcels.
// Run via: npx tsx scripts/fetch-gilbert-parcels.ts
//
// Uses OBJECTID-based pagination to work around MapServer's silent
// maxRecordCount cap (1000). All non-trivial logic lives in
// ./lib/gilbert-fetch and is unit-tested.

import fs from "node:fs";
import zlib from "node:zlib";
import {
  stampFeature,
  enforceGzippedBudget,
  probeEndpoint,
  formatFailLoudMessage,
  chunkIds,
  hasAllRequiredApns,
  fetchObjectIds,
  fetchFeaturesByIdChunk,
  type Bbox,
} from "./lib/gilbert-fetch";

const BBOX: Bbox = {
  xmin: -111.755,
  ymin: 33.225,
  xmax: -111.695,
  ymax: 33.258,
};
const OUT_FIELDS = [
  "APN", "APN_DASH", "OWNER_NAME",
  "PHYSICAL_STREET_NUM", "PHYSICAL_STREET_DIR", "PHYSICAL_STREET_NAME",
  "PHYSICAL_STREET_TYPE", "PHYSICAL_CITY", "PHYSICAL_ZIP",
  "SUBNAME", "LOT_NUM", "DEED_NUMBER", "DEED_DATE", "SALE_DATE",
  "LAND_SIZE", "CONST_YEAR", "Shape_Length", "Shape_Area",
].join(",");
const BUDGET = 2 * 1024 * 1024;
const CHUNK_SIZE = 500;

// MapServer confirmed working (2026-04-16). FeatureServer returns
// 200-with-error-body — probeEndpoint accepts it but /0/query 500s.
// See CLAUDE.md Decision #43 notes.
const PROBE_URLS = [
  "https://gis.mcassessor.maricopa.gov/arcgis/rest/services/Parcels/MapServer",
  "https://maps.mcassessor.maricopa.gov/arcgis/rest/services/",
  "https://maps-mcassessor.opendata.arcgis.com/",
];
const LAYER_PATH = "/0";

const REQUIRED_APNS = [
  "304-78-386", // POPHAM
  "304-77-689", // HOGUE
  "304-78-409", // HOA tract
  "304-78-374", // WARNER
  "304-78-383", // LOWRY
] as const;

async function main() {
  // 1. Endpoint probe
  const probeRes = await probeEndpoint(PROBE_URLS, fetch);
  if (!probeRes.ok) {
    console.error(formatFailLoudMessage(PROBE_URLS));
    console.error("Probe attempts:");
    for (const a of probeRes.attempts) console.error(`  ${a.url}: ${a.error}`);
    process.exit(1);
  }
  const base = probeRes.base;
  console.log(`probe OK: ${base}`);

  // 2. Fetch all OBJECTIDs in the bbox
  console.log("fetching OBJECTID list...");
  const allIds = await fetchObjectIds(base, LAYER_PATH, BBOX, fetch);
  console.log(`${allIds.length} OBJECTIDs in bbox`);

  if (allIds.length === 0) {
    console.error(
      "ERROR: zero OBJECTIDs. Check bbox and layer path.",
    );
    process.exit(1);
  }

  // 3. Chunk and fetch features page by page
  const chunks = chunkIds(allIds, CHUNK_SIZE);
  console.log(`${chunks.length} chunks of up to ${CHUNK_SIZE} IDs`);

  const captured = new Date().toISOString().slice(0, 10);
  const all: unknown[] = [];
  const layerUrl = `${base}${LAYER_PATH}`;

  for (let i = 0; i < chunks.length; i++) {
    const chunk = chunks[i];
    const features = await fetchFeaturesByIdChunk(
      base, LAYER_PATH, chunk, OUT_FIELDS, fetch,
    );
    console.log(
      `chunk ${i + 1}/${chunks.length}: ${chunk.length} IDs → ${features.length} features`,
    );
    for (const f of features) {
      all.push(
        stampFeature(f as never, {
          source_url: layerUrl,
          captured_date: captured,
        }),
      );
    }
  }

  console.log(`total: ${all.length} features from ${allIds.length} OBJECTIDs`);

  // 4. Post-fetch integrity check (non-negotiable)
  const integrity = hasAllRequiredApns(
    all as Array<{ properties: Record<string, unknown> }>,
    REQUIRED_APNS,
  );
  if (!integrity.ok) {
    console.error(
      `ERROR: required APNs missing: ${integrity.missing.join(", ")}`,
    );
    console.error("Do NOT commit this seed.");
    process.exit(1);
  }
  console.log(
    `integrity: all ${REQUIRED_APNS.length} required APNs present`,
  );

  // 5. Assemble FeatureCollection + budget check
  const out = {
    type: "FeatureCollection" as const,
    metadata: {
      source: "maricopa_assessor_public_gis",
      source_url: layerUrl,
      captured_date: captured,
      record_count: all.length,
      bbox: BBOX,
      attribution: "Maricopa County Assessor",
      legal: "Public record per Arizona A.R.S. § 11-495",
      layer_endpoint: layerUrl,
      pagination: "OBJECTID-based",
      chunk_size: CHUNK_SIZE,
      objectid_count: allIds.length,
    },
    features: all,
  };

  const json = JSON.stringify(out);
  const gz = zlib.gzipSync(Buffer.from(json));
  enforceGzippedBudget(gz, BUDGET, { bbox: BBOX });

  // 6. Write files
  fs.writeFileSync("src/data/gilbert-parcels-geo.json", json);
  fs.writeFileSync(
    "src/data/gilbert-seed-count.ts",
    `// Generated by scripts/fetch-gilbert-parcels.ts on ${captured}.\n` +
      `// Source of truth for the landing "not in seeded area" copy.\n` +
      `export const SEED_COUNT = ${all.length};\n`,
  );

  console.log(
    `wrote ${all.length} features, ` +
      `${json.length} bytes raw, ` +
      `${gz.byteLength} bytes gzipped (budget ${BUDGET})`,
  );
}

main().catch((e) => {
  console.error((e as Error).message);
  process.exit(1);
});
