const GLOSSARY: Record<string, string> = {
  "chain of title": "Ownership History",
  "encumbrances": "Claims Against Property",
  "encumbrance lifecycles": "Claims Against Property",
  "lifecycle": "Claim Against Property",
  "lifecycles": "Claims Against Property",
  "deed of trust": "Mortgage",
  "full reconveyance": "Mortgage Paid Off",
  "partial reconveyance": "Partial Payoff",
  "warranty deed": "Sale Deed",
  "special warranty deed": "Sale Deed (Limited)",
  "quit claim deed": "Ownership Transfer",
  "grant deed": "Sale Deed",
  "grantor": "Seller",
  "grantee": "Buyer",
  "dot": "Mortgage",
  "assignment of dot": "Mortgage Transfer",
  "heloc dot": "Home Equity Loan",
  "trustor/borrower": "Borrower",
  "parcel": "property",
  "back-reference": "Citation",
  "back-references": "Citations",
  "citation": "Citation",
  "citations": "Citations",
  "cites": "Cites",
  "cited by": "Cited By",
  "inbound references": "Cited By",
  "outbound references": "Cites",
  "release": "Mortgage Paid Off",
  "modification": "Modification (Plain)",
  "assignment": "Mortgage Transfer",
  "deed": "Sale Deed",
  "mod.": "Modification (Plain)",
  "ucc-3": "UCC Termination",
  "affid.": "Affidavit",
  "sub.t.": "Sub. of Trustee",
};

export function translate(term: string): string {
  return GLOSSARY[term.toLowerCase()] ?? term;
}
