// Generated by scripts/fetch-gilbert-parcels.ts on 2026-04-16.
// 4 demo_synthesized scenario polygons appended by
// scripts/add-scenario-polygons.mjs (2026-04-18) — CHEN / MARTINEZ /
// DELGADO / BRYANT. Tagged `source: "demo_synthesized"` on each feature.
// Source of truth for the landing "not in seeded area" copy.
export const SEED_COUNT = 8574;
